# .goreleaser.yml
# Build customization
builds:
  - binary: dt
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386

# Changelog customization
changelog:
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - typo
      - (?i)foo
      - fmt
      - gofmt

# Archive customization
archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE.txt
    - README.md
    - examples/config-sample.yaml

# Homebrew customization
brew:
  name: dt
  github:
    owner: chclaus
    name: dt
  folder: Formula
  homepage: "https://github.com/chclaus/dt"
  description: "CLI tool for common dev tasks."
  install: |
    bin.install "dt"
    zsh_completion.install "dt-completion.zsh" => "_dt.zsh"
    bash_completion.install "dt-completion.bash"
