# .goreleaser.yml
# Build customization
builds:
  - binary: dt
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
# Archive customization
archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE.txt
    - README.md
